# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files
    paths:
      - '**.md'

# Allow the workflow to write files back to the repository
permissions:
  contents: write

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ./
          output_dir: ./
          build_html: false
          build_pdf: true
          table_of_contents: false
      - run: |
          REPO_NAME=$(basename ${{ github.repository }})
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          mv "README.pdf" "$REPO_NAME.pdf"
      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${{ env.REPO_NAME }}.pdf"
          # Commit only if there are changes; avoid failing when nothing changed
          git diff --staged --quiet || git commit -m "${{ env.REPO_NAME }}.pdf gerado automaticamente"
          git push
#      - uses: actions/upload-artifact@v4
#        with:
#          name: ${{ env.REPO_NAME }}
#          path: './**.pdf'
